### ISSUE TITLE
コマンドエラー

### ISSUE THREAD

**Issue by popkechupki** [JupiterDevelopmentTeam/JupiterDevelopmentTeam#1]
起動時に以下のエラーメッセージ
`[ALERT] java.lang.NullPointerException
	at cn.nukkit.command.SimpleCommandMap.setDefaultCommands(SimpleCommandMap.java:81)
	at cn.nukkit.command.SimpleCommandMap.<init>(SimpleCommandMap.java:77)
	at cn.nukkit.Server.<init>(Server.java:485)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
`

**Comment by itsu020402** [comment]
Jupiter.ymlにない値を参照しているのでJupiter.ymlを削除して再生成をさせてみてください。

**Comment by popkechupki** [comment]
うまく生成されない（中身が書き込まれてない）んですがこれはこちらのミスでしょうか

**Comment by itsu020402** [comment]
その場合は他のフォルダもすべて削除して一から起動すると解決すると思います。

**Comment by Megapix96** [comment]
さっき直しました
正常に書き込まれていないバグでした すみません
