### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NycuRO** [JupiterDevelopmentTeam/JupiterDevelopmentTeam#7]
15:25:02 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
15:25:02 [ALERT] java.lang.NullPointerException
        at cn.nukkit.Player.kill(Player.java:4501)
        at cn.nukkit.entity.Entity.setHealth(Entity.java:837)
        at cn.nukkit.entity.EntityLiving.setHealth(EntityLiving.java:68)
        at cn.nukkit.Player.setHealth(Player.java:4548)
        at cn.nukkit.entity.Entity.attack(Entity.java:803)
        at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:107)
        at cn.nukkit.entity.EntityHumanType.attack(EntityHumanType.java:150)
        at cn.nukkit.Player.attack(Player.java:4711)
        at cn.nukkit.level.Explosion.explodeB(Explosion.java:158)
        at cn.nukkit.entity.item.EntityPrimedTNT.explode(EntityPrimedTNT.java:158)
        at cn.nukkit.entity.item.EntityPrimedTNT.onUpdate(EntityPrimedTNT.java:137)
        at cn.nukkit.level.Level.doTick(Level.java:831)
        at cn.nukkit.Server.checkTickUpdates(Server.java:1403)
        at cn.nukkit.Server.tick(Server.java:1478)
        at cn.nukkit.Server.tickProcessor(Server.java:1265)
        at cn.nukkit.Server.start(Server.java:1244)
        at cn.nukkit.Server.<init>(Server.java:731)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by itsu020402** [comment]
When did this happen?

**Comment by itsu020402** [comment]
I'm very sorry.
fixed.

**Comment by NycuRO** [comment]
Not fixed.

**Comment by itsu020402** [comment]
I'll check it.

**Comment by itsu020402** [comment]
When did it happen?
I happened it when I executed that command of "/kill, /kill <player>".
But fixed it now.

**Comment by NycuRO** [comment]
By tnt.

**Comment by NycuRO** [comment]
Can you update Software with this changes: https://github.com/Nukkit/Nukkit/commits/changes-04-17

@itsu020402

**Comment by itsu020402** [comment]
Thanks.
I'll challenge to fix it.

**Comment by itsu020402** [comment]
Maybe I fixed it.
If the bug doesn't fix, please tell me again.
